language: elixir
dist: trusty
elixir:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
otp_release:
  - 18.3
  - 19.3
  - 20.1
matrix:
  exclude:
    elixir: 1.3
    otp_release: 20.1

sudo: false
env:
  global:
    - STRIPE_MOCK_VERSION=0.14.0
    - MIX_ENV=test STRIPE_SECRET_KEY=non_empty_secret_key_string
cache:
  directories:
    - stripe-mock
before_install:
  - |
      if [ ! -d "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}" ]; then
        mkdir -p stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/
        curl -L "https://github.com/stripe/stripe-mock/releases/download/v${STRIPE_MOCK_VERSION}/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz" -o "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz"
        tar -zxf "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz" -C "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/"
      fi
  - export PATH=$PATH:$PWD/stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/
script: mix coveralls.travis
after_script:
  - mix inch.report
notifications:
  email:
    on_success: never
