language: elixir
dist: trusty
elixir:
  - 1.7
  - 1.8
  - 1.9
otp_release:
  - 19.3
  - 20.1
  - 21.1
matrix:
  exclude:
    - otp_release: 19.3
      elixir: 1.8
    - otp_release: 19.3
      elixir: 1.9
sudo: false
env:
  global:
    - STRIPE_MOCK_VERSION=0.70.0
    - MIX_ENV=test STRIPE_SECRET_KEY=non_empty_secret_key_string
cache:
  directories:
    - priv/plts
    - stripe-mock
before_install:
  - |
      if [ ! -d "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}" ]; then
        mkdir -p stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/
        curl -L "https://github.com/stripe/stripe-mock/releases/download/v${STRIPE_MOCK_VERSION}/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz" -o "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz"
        tar -zxf "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz" -C "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/"
      fi
  - export PATH=$PATH:$PWD/stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/
script:
  - |
      if [ "$TRAVIS_ELIXIR_VERSION" == "1.8" ]; then
        mix format --dry-run --check-formatted;
      fi
  - mix coveralls.travis
  - MIX_ENV=dev mix dialyzer --halt-exit-status
after_script:
  - mix inch.report
notifications:
  email:
    on_success: never
